/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Resume;
import Business.ResumeHistory;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author mac
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private ResumeHistory rsh;
    public Resume rs=new Resume();
    public CreateJPanel(ResumeHistory rsh) {
        initComponents();
        this.rsh=rsh;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNamjLabel = new javax.swing.JLabel();
        lastNamjLabel = new javax.swing.JLabel();
        firstnameTextField = new javax.swing.JTextField();
        lastnameTextField = new javax.swing.JTextField();
        addressjLabel = new javax.swing.JLabel();
        addcityTextField = new javax.swing.JTextField();
        affiliationjLabel = new javax.swing.JLabel();
        objstatejLabel = new javax.swing.JLabel();
        phoneNumjLabel = new javax.swing.JLabel();
        phoneNumTextField = new javax.swing.JTextField();
        workhistoryjLabel = new javax.swing.JLabel();
        abilityjLabel = new javax.swing.JLabel();
        affiliationTextField = new javax.swing.JTextField();
        genderjLabel = new javax.swing.JLabel();
        imgjLabel = new javax.swing.JLabel();
        imgBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        gender_F_RBtn = new javax.swing.JRadioButton();
        gender_M_RBtn = new javax.swing.JRadioButton();
        eduunder_TextField = new javax.swing.JTextField();
        eduhigh_ComboBox = new javax.swing.JComboBox<>();
        eduhigh_TextField = new javax.swing.JTextField();
        edujLabel = new javax.swing.JLabel();
        edugrad_ComboBox = new javax.swing.JComboBox<>();
        edugrad_TextField = new javax.swing.JTextField();
        eduunder_ComboBox = new javax.swing.JComboBox<>();
        objstateTextField = new javax.swing.JTextField();
        workhisjScrollPane = new javax.swing.JScrollPane();
        workhisTextArea = new javax.swing.JTextArea();
        saveBtn = new javax.swing.JButton();
        addline1TextField = new javax.swing.JTextField();
        citizenRBtn = new javax.swing.JRadioButton();
        internationalRBtn = new javax.swing.JRadioButton();
        javajCheckBox = new javax.swing.JCheckBox();
        htmljCheckBox = new javax.swing.JCheckBox();
        nonejCheckBox = new javax.swing.JCheckBox();
        redjLabel1 = new javax.swing.JLabel();
        redjLabel2 = new javax.swing.JLabel();
        redjLabel3 = new javax.swing.JLabel();
        redjLabel4 = new javax.swing.JLabel();
        redjLabel5 = new javax.swing.JLabel();
        studentRBtn = new javax.swing.JRadioButton();
        nonstudentRBtn = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emailjLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        redjLabel6 = new javax.swing.JLabel();

        firstNamjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        firstNamjLabel.setText("First Name:");

        lastNamjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lastNamjLabel.setText("Last Name:");

        firstnameTextField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        lastnameTextField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        addressjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        addressjLabel.setText("Address:");

        addcityTextField.setForeground(new java.awt.Color(153, 153, 153));
        addcityTextField.setText("City");
        addcityTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addcityTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addcityTextFieldFocusLost(evt);
            }
        });

        affiliationjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        affiliationjLabel.setText("Affiliation:");

        objstatejLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        objstatejLabel.setText("Carrer object statement:");

        phoneNumjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        phoneNumjLabel.setText("Phone Number:");

        phoneNumTextField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        phoneNumTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        workhistoryjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        workhistoryjLabel.setText("Work History:");

        abilityjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        abilityjLabel.setText("Ability:");

        affiliationTextField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        genderjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        genderjLabel.setText("Gender:");

        imgjLabel.setBackground(new java.awt.Color(255, 255, 255));
        imgjLabel.setForeground(new java.awt.Color(255, 255, 255));
        imgjLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255)));

        imgBtn.setText("choose");
        imgBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgBtnMouseClicked(evt);
            }
        });
        imgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgBtnActionPerformed(evt);
            }
        });

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        gender_F_RBtn.setText("Female");
        gender_F_RBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender_F_RBtnActionPerformed(evt);
            }
        });

        gender_M_RBtn.setText("Male");
        gender_M_RBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender_M_RBtnActionPerformed(evt);
            }
        });

        eduhigh_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High school", "Undergraduate", "Graduate" }));
        eduhigh_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eduhigh_ComboBoxActionPerformed(evt);
            }
        });

        edujLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        edujLabel.setText("Education:");

        edugrad_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High school", "Undergraduate", "Graduate" }));
        edugrad_ComboBox.setSelectedIndex(2);
        edugrad_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edugrad_ComboBoxActionPerformed(evt);
            }
        });

        eduunder_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High school", "Undergraduate", "Graduate" }));
        eduunder_ComboBox.setSelectedIndex(1);
        eduunder_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eduunder_ComboBoxActionPerformed(evt);
            }
        });

        workhisTextArea.setColumns(20);
        workhisTextArea.setRows(5);
        workhisjScrollPane.setViewportView(workhisTextArea);

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        addline1TextField.setForeground(new java.awt.Color(153, 153, 153));
        addline1TextField.setText("Address line:");
        addline1TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addline1TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addline1TextFieldFocusLost(evt);
            }
        });
        addline1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addline1TextFieldActionPerformed(evt);
            }
        });

        citizenRBtn.setText("Citizen");
        citizenRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citizenRBtnActionPerformed(evt);
            }
        });

        internationalRBtn.setText("International");
        internationalRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internationalRBtnActionPerformed(evt);
            }
        });

        javajCheckBox.setText("JAVA");
        javajCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                javajCheckBoxActionPerformed(evt);
            }
        });

        htmljCheckBox.setText("HTML");
        htmljCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htmljCheckBoxActionPerformed(evt);
            }
        });

        nonejCheckBox.setText("None of them");
        nonejCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonejCheckBoxActionPerformed(evt);
            }
        });

        redjLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        redjLabel1.setForeground(new java.awt.Color(255, 0, 0));
        redjLabel1.setText("*");

        redjLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        redjLabel2.setForeground(new java.awt.Color(255, 0, 0));
        redjLabel2.setText("*");

        redjLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        redjLabel3.setForeground(new java.awt.Color(255, 0, 0));
        redjLabel3.setText("*");

        redjLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        redjLabel4.setForeground(new java.awt.Color(255, 0, 0));
        redjLabel4.setText("*");

        redjLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        redjLabel5.setForeground(new java.awt.Color(255, 0, 0));
        redjLabel5.setText("*");

        studentRBtn.setText("Student");
        studentRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentRBtnActionPerformed(evt);
            }
        });

        nonstudentRBtn.setText("Non-student");
        nonstudentRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonstudentRBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel1.setText("Current situation:");

        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("only numbers");

        emailjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        emailjLabel.setText("Email:");

        emailTextField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        emailTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        redjLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        redjLabel6.setForeground(new java.awt.Color(255, 0, 0));
        redjLabel6.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(objstatejLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(abilityjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(23, 23, 23)
                                    .addComponent(javajCheckBox)
                                    .addGap(31, 31, 31)
                                    .addComponent(htmljCheckBox)
                                    .addGap(32, 32, 32)
                                    .addComponent(nonejCheckBox)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(redjLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(97, 97, 97)
                                    .addComponent(objstateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(emailjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(phoneNumjLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(phoneNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(redjLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(redjLabel4)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(genderjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(gender_F_RBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(gender_M_RBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(redjLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(firstNamjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lastNamjLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(redjLabel1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(redjLabel2))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(128, 128, 128)
                                        .addComponent(nonstudentRBtn))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(workhistoryjLabel)
                                            .addGap(276, 276, 276))
                                        .addComponent(workhisjScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(studentRBtn)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(edujLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(16, 16, 16)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(eduhigh_ComboBox, 0, 1, Short.MAX_VALUE)
                                                        .addComponent(eduunder_ComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 1, Short.MAX_VALUE)
                                                        .addComponent(edugrad_ComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(eduunder_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(edugrad_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(eduhigh_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addressjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(affiliationjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(affiliationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(citizenRBtn)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(internationalRBtn))
                                            .addComponent(addline1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addcityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17))))
            .addGroup(layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(submitBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(imgjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(imgBtn)
                            .addComponent(saveBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(firstNamjLabel)
                                    .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastNamjLabel))
                                .addGap(4, 4, 4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(redjLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(redjLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderjLabel)
                            .addComponent(gender_F_RBtn)
                            .addComponent(gender_M_RBtn)
                            .addComponent(redjLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(phoneNumjLabel)
                                .addComponent(phoneNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addComponent(redjLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailjLabel)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(redjLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(internationalRBtn)
                            .addComponent(citizenRBtn)
                            .addComponent(addressjLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addline1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addcityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(affiliationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(affiliationjLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(studentRBtn)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(nonstudentRBtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edujLabel)
                            .addComponent(edugrad_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edugrad_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eduunder_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eduunder_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eduhigh_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eduhigh_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workhistoryjLabel)
                .addGap(4, 4, 4)
                .addComponent(workhisjScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abilityjLabel)
                    .addComponent(javajCheckBox)
                    .addComponent(htmljCheckBox)
                    .addComponent(nonejCheckBox)
                    .addComponent(redjLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(objstatejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(objstateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitBtn))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        String firstText=firstnameTextField.getText();
        String lastText=lastnameTextField.getText();
        String phoneText=phoneNumTextField.getText();
        String emailText=emailTextField.getText();
        String add1Text=addline1TextField.getText();
        String cityText=addcityTextField.getText();
        
        String AffiliationText=affiliationTextField.getText();
        String eduhighText=edugrad_TextField.getText();
        String eduunderText=eduunder_TextField.getText();
        String edugraduateText=eduhigh_TextField.getText();
        
        String workhistoryText=workhisTextArea.getText();
        String objtText=objstateTextField.getText();
        
        String eduhighcombox=edugrad_ComboBox.getSelectedItem().toString();
        String eduundercombox=eduunder_ComboBox.getSelectedItem().toString();
        String edugradcombox=eduhigh_ComboBox.getSelectedItem().toString();
        if(firstText.isEmpty()||lastText.isEmpty()||phoneText.isEmpty()||((!gender_M_RBtn.isSelected())&&(!gender_F_RBtn.isSelected()))||((!javajCheckBox.isSelected())&&(!htmljCheckBox.isSelected())&&(!nonejCheckBox.isSelected())))
        {
            JOptionPane.showMessageDialog(this, "Field text with * must fill all !", null, JOptionPane.ERROR_MESSAGE);
            return;
        }
        String reg="^[0-9]*$";
     //   String reg="^[0-9]{10}$";
        if(!phoneText.matches(reg))
        {
            JOptionPane.showMessageDialog(this, "Wrong format of phone number", null, JOptionPane.ERROR_MESSAGE);
            return;
        }
        String regemail="^([a-z0-9A-Z]+[-|\\\\\\\\.]?)+[a-z0-9A-Z]@([a-z0-9A-Z]+([-.]?[a-z0-9A-Z]+)?\\.)+[a-zA-Z]{2,}$";
        if(!emailText.matches(regemail))
        {
            JOptionPane.showMessageDialog(this, "Wrong format of email", null, JOptionPane.ERROR_MESSAGE);
            return;
        }
        rs=rsh.addResume();             //************************//
        rs.setFirstname(firstText);
        rs.setLastname(lastText);
        
        if(gender_F_RBtn.isSelected())
        {
            rs.setGender(gender_F_RBtn.getText());
        }
        else if(gender_M_RBtn.isSelected())
        {
            rs.setGender(gender_M_RBtn.getText());
        }
        rs.setPhonenum(Long.parseLong(phoneText));
        rs.setEmail(emailText);
        
        if(citizenRBtn.isSelected())
        {rs.setAddresschoice(citizenRBtn.getText());}
        else if(internationalRBtn.isSelected())
        {rs.setAddresschoice(internationalRBtn.getText());}
        
        rs.setAddress_1(add1Text);
        rs.setAddress_city(cityText);
        rs.setAffiliation(AffiliationText);
        if(studentRBtn.isSelected())
        {rs.setCurrent(studentRBtn.getText());}
        if(nonstudentRBtn.isSelected())
        {rs.setCurrent(nonstudentRBtn.getText());}
        rs.setEdu_highcombox(eduhighcombox);
        rs.setEdu_high(eduhighText);
        rs.setEdu_undercombox(eduundercombox);
        rs.setEdu_under(eduunderText);
        rs.setEdu_gradcombox(edugradcombox);
        rs.setEdu_graduate(edugraduateText);
        rs.setWorkhistory(workhistoryText);
        
        if(javajCheckBox.isSelected())
        {rs.setAbility(javajCheckBox.getText());}
        if(htmljCheckBox.isSelected())
        {rs.setAbility(htmljCheckBox.getText());}
        if(nonejCheckBox.isSelected())
        {rs.setAbility(nonejCheckBox.getText());}
        if((javajCheckBox.isSelected())&&(htmljCheckBox.isSelected()))
        {rs.setAbility(javajCheckBox.getText()+"/"+htmljCheckBox.getText());}
        
        rs.setCarreerobjst(objtText);
        rs.setIcon(imgjLabel.getIcon());
        JOptionPane.showMessageDialog(null,"Submit Successfully!");
        
        
        firstnameTextField.setText("");
        lastnameTextField.setText("");
        phoneNumTextField.setText("");
        emailTextField.setText("");
        addline1TextField.setText("Address line:");
        addline1TextField.setForeground(Color.gray);
        addcityTextField.setText("City");
        addcityTextField.setForeground(Color.gray);
        affiliationTextField.setText("");
        edugrad_TextField.setText("");
        eduunder_TextField.setText("");
        eduhigh_TextField.setText("");
        workhisTextArea.setText("");
        objstateTextField.setText("");
        gender_F_RBtn.setSelected(false);
        gender_M_RBtn.setSelected(false);
        studentRBtn.setSelected(false);
        nonstudentRBtn.setSelected(false);
        javajCheckBox.setSelected(false);
        htmljCheckBox.setSelected(false);
        nonejCheckBox.setSelected(false);
        citizenRBtn.setSelected(false);
        internationalRBtn.setSelected(false);
        imgjLabel.setIcon(null);
    }//GEN-LAST:event_submitBtnActionPerformed
    
    public ImageIcon ResizeImage(String ImagePath)
    {
       ImageIcon icon=new ImageIcon(ImagePath);
       Image img=icon.getImage();
       Image newImg=img.getScaledInstance(imgjLabel.getWidth(), imgjLabel.getHeight(), Image.SCALE_SMOOTH);
       ImageIcon imgcon=new ImageIcon(newImg);
       
       return imgcon;
    }
    private void imgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null); 
        File f=chooser.getSelectedFile();
        String filepath=f.getAbsolutePath();
        imgjLabel.setIcon(ResizeImage(filepath)); 
    }//GEN-LAST:event_imgBtnActionPerformed

    private void imgBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_imgBtnMouseClicked

    private void gender_F_RBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gender_F_RBtnActionPerformed
        if(gender_F_RBtn.isSelected())
        {
            gender_M_RBtn.setSelected(false);
        }
    }//GEN-LAST:event_gender_F_RBtnActionPerformed

    private void gender_M_RBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gender_M_RBtnActionPerformed
        if(gender_M_RBtn.isSelected())
        {
            gender_F_RBtn.setSelected(false);
        }
    }//GEN-LAST:event_gender_M_RBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        JOptionPane.showMessageDialog(null,"Save the picture");
    }//GEN-LAST:event_saveBtnActionPerformed

    private void edugrad_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edugrad_ComboBoxActionPerformed
    }//GEN-LAST:event_edugrad_ComboBoxActionPerformed

    private void eduunder_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eduunder_ComboBoxActionPerformed
    }//GEN-LAST:event_eduunder_ComboBoxActionPerformed

    private void eduhigh_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eduhigh_ComboBoxActionPerformed

    }//GEN-LAST:event_eduhigh_ComboBoxActionPerformed

    private void addline1TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addline1TextFieldFocusGained
        if(addline1TextField.getText().equals("Address line:"))
        {   addline1TextField.setText("");
            addline1TextField.setForeground(Color.black);}
    }//GEN-LAST:event_addline1TextFieldFocusGained

    private void addline1TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addline1TextFieldFocusLost
        if(addline1TextField.getText().isEmpty())
        {
            addline1TextField.setForeground(Color.gray);
            addline1TextField.setText("Address line:");
        }   
    }//GEN-LAST:event_addline1TextFieldFocusLost

    private void addline1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addline1TextFieldActionPerformed
    }//GEN-LAST:event_addline1TextFieldActionPerformed

    private void addcityTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addcityTextFieldFocusGained
        if(addcityTextField.getText().equals("City"))
        {   addcityTextField.setText("");
            addcityTextField.setForeground(Color.black);
        }
    }//GEN-LAST:event_addcityTextFieldFocusGained

    private void addcityTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addcityTextFieldFocusLost
        if(addcityTextField.getText().isEmpty())
        {
            addcityTextField.setForeground(Color.gray);
            addcityTextField.setText("City");
        }
    }//GEN-LAST:event_addcityTextFieldFocusLost

    private void citizenRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citizenRBtnActionPerformed
        if(citizenRBtn.isSelected())
        {internationalRBtn.setSelected(false);}
    }//GEN-LAST:event_citizenRBtnActionPerformed

    private void internationalRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internationalRBtnActionPerformed
        if(internationalRBtn.isSelected())
        {citizenRBtn.setSelected(false);}
    }//GEN-LAST:event_internationalRBtnActionPerformed

    private void studentRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentRBtnActionPerformed
        if(studentRBtn.isSelected())
        {nonstudentRBtn.setSelected(false);}
    }//GEN-LAST:event_studentRBtnActionPerformed

    private void nonstudentRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonstudentRBtnActionPerformed
        if(nonstudentRBtn.isSelected())
        {studentRBtn.setSelected(false);}
    }//GEN-LAST:event_nonstudentRBtnActionPerformed

    private void nonejCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonejCheckBoxActionPerformed
        if(nonejCheckBox.isSelected())
        {
            javajCheckBox.setSelected(false);
            htmljCheckBox.setSelected(false);
        }
    }//GEN-LAST:event_nonejCheckBoxActionPerformed

    private void javajCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javajCheckBoxActionPerformed
        if(javajCheckBox.isSelected())
        {
            nonejCheckBox.setSelected(false);
        }
    }//GEN-LAST:event_javajCheckBoxActionPerformed

    private void htmljCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htmljCheckBoxActionPerformed
        if(htmljCheckBox.isSelected())
        {
            nonejCheckBox.setSelected(false);
        }
    }//GEN-LAST:event_htmljCheckBoxActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abilityjLabel;
    private javax.swing.JTextField addcityTextField;
    private javax.swing.JTextField addline1TextField;
    private javax.swing.JLabel addressjLabel;
    private javax.swing.JTextField affiliationTextField;
    private javax.swing.JLabel affiliationjLabel;
    private javax.swing.JRadioButton citizenRBtn;
    private javax.swing.JComboBox<String> edugrad_ComboBox;
    private javax.swing.JTextField edugrad_TextField;
    private javax.swing.JComboBox<String> eduhigh_ComboBox;
    private javax.swing.JTextField eduhigh_TextField;
    private javax.swing.JLabel edujLabel;
    private javax.swing.JComboBox<String> eduunder_ComboBox;
    private javax.swing.JTextField eduunder_TextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel emailjLabel;
    private javax.swing.JLabel firstNamjLabel;
    private javax.swing.JTextField firstnameTextField;
    private javax.swing.JRadioButton gender_F_RBtn;
    private javax.swing.JRadioButton gender_M_RBtn;
    private javax.swing.JLabel genderjLabel;
    private javax.swing.JCheckBox htmljCheckBox;
    private javax.swing.JButton imgBtn;
    private javax.swing.JLabel imgjLabel;
    private javax.swing.JRadioButton internationalRBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox javajCheckBox;
    private javax.swing.JLabel lastNamjLabel;
    private javax.swing.JTextField lastnameTextField;
    private javax.swing.JCheckBox nonejCheckBox;
    private javax.swing.JRadioButton nonstudentRBtn;
    private javax.swing.JTextField objstateTextField;
    private javax.swing.JLabel objstatejLabel;
    private javax.swing.JTextField phoneNumTextField;
    private javax.swing.JLabel phoneNumjLabel;
    private javax.swing.JLabel redjLabel1;
    private javax.swing.JLabel redjLabel2;
    private javax.swing.JLabel redjLabel3;
    private javax.swing.JLabel redjLabel4;
    private javax.swing.JLabel redjLabel5;
    private javax.swing.JLabel redjLabel6;
    private javax.swing.JButton saveBtn;
    private javax.swing.JRadioButton studentRBtn;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextArea workhisTextArea;
    private javax.swing.JScrollPane workhisjScrollPane;
    private javax.swing.JLabel workhistoryjLabel;
    // End of variables declaration//GEN-END:variables
}
