/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Resume;
import Business.ResumeHistory;
import javax.swing.Icon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mac
 */
public class ViewTableJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewTableJPanel
     */
    private ResumeHistory rsh;
    public ViewTableJPanel(ResumeHistory rsh) {
        initComponents();
        this.rsh=rsh;
        populateTable();
    }
    
    public void populateTable() 
    {
        DefaultTableModel dtm= (DefaultTableModel) viewjTable.getModel();
        dtm.setRowCount(0);
        for(Resume rs : rsh.getResumeHistory())
        {
            Object row[]=new Object[4];
            row[0]=rs;
            row[1]=rs.getLastname();
            row[2]=rs.getGender();
            row[3]=rs.getPhonenum();
      
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewjScrollPane = new javax.swing.JScrollPane();
        viewjPanel = new javax.swing.JPanel();
        viewjLabel = new javax.swing.JLabel();
        viewBtn = new javax.swing.JButton();
        viewjScrollPane1 = new javax.swing.JScrollPane();
        viewjTable = new javax.swing.JTable();
        eduhigh_ComboBox = new javax.swing.JComboBox<>();
        eduhigh_TextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        edujLabel = new javax.swing.JLabel();
        workhisjScrollPane = new javax.swing.JScrollPane();
        workhisTextArea = new javax.swing.JTextArea();
        phoneNumjLabel = new javax.swing.JLabel();
        addline1TextField = new javax.swing.JTextField();
        phoneNumTextField = new javax.swing.JTextField();
        workhistoryjLabel = new javax.swing.JLabel();
        abilityjLabel = new javax.swing.JLabel();
        affiliationTextField = new javax.swing.JTextField();
        addressjLabel = new javax.swing.JLabel();
        addcityTextField = new javax.swing.JTextField();
        affiliationjLabel = new javax.swing.JLabel();
        objstatejLabel = new javax.swing.JLabel();
        eduunder_TextField = new javax.swing.JTextField();
        genderjLabel = new javax.swing.JLabel();
        namejLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        genderTextField = new javax.swing.JTextField();
        addrTextField = new javax.swing.JTextField();
        currentTextField = new javax.swing.JTextField();
        abilityTextField = new javax.swing.JTextField();
        imgjLabel = new javax.swing.JLabel();
        edugrad_TextField = new javax.swing.JTextField();
        edugrad_ComboBox = new javax.swing.JComboBox<>();
        eduunder_ComboBox = new javax.swing.JComboBox<>();
        objstatejScrollPane = new javax.swing.JScrollPane();
        objstateTextArea = new javax.swing.JTextArea();
        emailjLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(240, 243, 243));

        viewjScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        viewjLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        viewjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewjLabel.setText("View Resumes");

        viewBtn.setText("View details");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        viewjScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        viewjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Gender", "Phone Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        viewjScrollPane1.setViewportView(viewjTable);

        eduhigh_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High school", "Undergraduate", "Graduate" }));
        eduhigh_ComboBox.setEnabled(false);
        eduhigh_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eduhigh_ComboBoxActionPerformed(evt);
            }
        });

        eduhigh_TextField.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel1.setText("Current situation:");

        edujLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        edujLabel.setText("Education:");

        workhisTextArea.setEditable(false);
        workhisTextArea.setColumns(20);
        workhisTextArea.setRows(5);
        workhisjScrollPane.setViewportView(workhisTextArea);

        phoneNumjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        phoneNumjLabel.setText("Phone Number:");

        addline1TextField.setEditable(false);
        addline1TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addline1TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addline1TextFieldFocusLost(evt);
            }
        });
        addline1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addline1TextFieldActionPerformed(evt);
            }
        });

        phoneNumTextField.setEditable(false);
        phoneNumTextField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        workhistoryjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        workhistoryjLabel.setText("Work History:");

        abilityjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        abilityjLabel.setText("Ability:");

        affiliationTextField.setEditable(false);
        affiliationTextField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        addressjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        addressjLabel.setText("Address:");

        addcityTextField.setEditable(false);
        addcityTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addcityTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addcityTextFieldFocusLost(evt);
            }
        });

        affiliationjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        affiliationjLabel.setText("Affiliation:");

        objstatejLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        objstatejLabel.setText("Carrer object statement:");

        eduunder_TextField.setEditable(false);

        genderjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        genderjLabel.setText("Gender:");

        namejLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        namejLabel.setText("Name:");

        nameTextField.setEditable(false);
        nameTextField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        genderTextField.setEditable(false);
        genderTextField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        addrTextField.setEditable(false);
        addrTextField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        currentTextField.setEditable(false);
        currentTextField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        abilityTextField.setEditable(false);
        abilityTextField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        imgjLabel.setBackground(new java.awt.Color(255, 255, 255));
        imgjLabel.setForeground(new java.awt.Color(255, 255, 255));
        imgjLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        edugrad_TextField.setEditable(false);

        edugrad_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High school", "Undergraduate", "Graduate" }));
        edugrad_ComboBox.setSelectedIndex(2);
        edugrad_ComboBox.setEnabled(false);

        eduunder_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High school", "Undergraduate", "Graduate" }));
        eduunder_ComboBox.setSelectedIndex(1);
        eduunder_ComboBox.setEnabled(false);

        objstateTextArea.setEditable(false);
        objstateTextArea.setColumns(20);
        objstateTextArea.setRows(5);
        objstatejScrollPane.setViewportView(objstateTextArea);

        emailjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        emailjLabel.setText("Email:");

        emailTextField.setEditable(false);
        emailTextField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        emailTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewjPanelLayout = new javax.swing.GroupLayout(viewjPanel);
        viewjPanel.setLayout(viewjPanelLayout);
        viewjPanelLayout.setHorizontalGroup(
            viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewjPanelLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(viewjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(viewjPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(objstatejLabel)
                    .addComponent(abilityjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(viewjPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewjPanelLayout.createSequentialGroup()
                        .addComponent(workhistoryjLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(viewjPanelLayout.createSequentialGroup()
                        .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewjPanelLayout.createSequentialGroup()
                                .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(viewjPanelLayout.createSequentialGroup()
                                        .addGap(182, 182, 182)
                                        .addComponent(viewBtn))
                                    .addGroup(viewjPanelLayout.createSequentialGroup()
                                        .addComponent(addressjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addline1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(viewjPanelLayout.createSequentialGroup()
                                        .addComponent(emailjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                .addComponent(imgjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(viewjPanelLayout.createSequentialGroup()
                                .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(viewjPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(currentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(viewjPanelLayout.createSequentialGroup()
                                        .addComponent(edujLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(abilityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(viewjPanelLayout.createSequentialGroup()
                                                .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(edugrad_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(eduunder_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(eduhigh_ComboBox, 0, 1, Short.MAX_VALUE))
                                                .addGap(14, 14, 14)
                                                .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(eduunder_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                                    .addComponent(eduhigh_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                                    .addComponent(edugrad_TextField)))
                                            .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(objstatejScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(workhisjScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(viewjPanelLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(viewjPanelLayout.createSequentialGroup()
                                                .addComponent(phoneNumjLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(phoneNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(viewjPanelLayout.createSequentialGroup()
                                                    .addComponent(namejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(24, 24, 24)
                                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(viewjPanelLayout.createSequentialGroup()
                                                    .addComponent(genderjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(viewjScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(41, 41, 41))
                    .addGroup(viewjPanelLayout.createSequentialGroup()
                        .addComponent(affiliationjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addcityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(affiliationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        viewjPanelLayout.setVerticalGroup(
            viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewjScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewjPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namejLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderjLabel)
                            .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneNumjLabel)
                            .addComponent(phoneNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailjLabel)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressjLabel)
                            .addComponent(addrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addline1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addcityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(affiliationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(affiliationjLabel))
                        .addGap(6, 6, 6))
                    .addGroup(viewjPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(imgjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(currentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edujLabel)
                    .addComponent(edugrad_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edugrad_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eduunder_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eduunder_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eduhigh_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eduhigh_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(workhistoryjLabel)
                .addGap(7, 7, 7)
                .addComponent(workhisjScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abilityjLabel)
                    .addComponent(abilityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(objstatejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(objstatejScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        viewjScrollPane.setViewportView(viewjPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewjScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(viewjScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        int selectedrow = viewjTable.getSelectedRow();
        if(selectedrow>=0)
        {
            Resume re = (Resume) viewjTable.getValueAt(selectedrow, 0);

            nameTextField.setText(re.getFirstname()+" "+re.getLastname());
            genderTextField.setText(re.getGender());
            phoneNumTextField.setText(String.valueOf(re.getPhonenum()));
            emailTextField.setText(re.getEmail());
            addrTextField.setText(re.getAddresschoice());
            if(re.getAddress_1().equals("Address line:"))
            {
                addline1TextField.setText("");
            }
            else
            {
                addline1TextField.setText(re.getAddress_1());
            }
            if(re.getAddress_city().equals("City"))
            {
                addcityTextField.setText("");
            }
            else
            {
                addcityTextField.setText(re.getAddress_city());
            }
            affiliationTextField.setText(re.getAffiliation());
            currentTextField.setText(re.getCurrent());
            
            edugrad_ComboBox.setSelectedItem(re.getEdu_gradcombox());
            edugrad_TextField.setText(re.getEdu_graduate());
            eduunder_ComboBox.setSelectedItem(re.getEdu_undercombox());
            eduunder_TextField.setText(re.getEdu_under());
            eduhigh_ComboBox.setSelectedItem(re.getEdu_highcombox());
            eduhigh_TextField.setText(re.getEdu_high());
            workhisTextArea.setText(re.getWorkhistory());
            abilityTextField.setText(re.getAbility());
            objstateTextArea.setText(re.getCarreerobjst());
            Icon image=re.getIcon();
            imgjLabel.setIcon(image);
        }
    }//GEN-LAST:event_viewBtnActionPerformed

    private void eduhigh_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eduhigh_ComboBoxActionPerformed

    }//GEN-LAST:event_eduhigh_ComboBoxActionPerformed

    private void addline1TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addline1TextFieldFocusGained

    }//GEN-LAST:event_addline1TextFieldFocusGained

    private void addline1TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addline1TextFieldFocusLost

    }//GEN-LAST:event_addline1TextFieldFocusLost

    private void addline1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addline1TextFieldActionPerformed

    }//GEN-LAST:event_addline1TextFieldActionPerformed

    private void addcityTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addcityTextFieldFocusGained

    }//GEN-LAST:event_addcityTextFieldFocusGained

    private void addcityTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addcityTextFieldFocusLost

    }//GEN-LAST:event_addcityTextFieldFocusLost

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField abilityTextField;
    private javax.swing.JLabel abilityjLabel;
    private javax.swing.JTextField addcityTextField;
    private javax.swing.JTextField addline1TextField;
    private javax.swing.JTextField addrTextField;
    private javax.swing.JLabel addressjLabel;
    private javax.swing.JTextField affiliationTextField;
    private javax.swing.JLabel affiliationjLabel;
    private javax.swing.JTextField currentTextField;
    private javax.swing.JComboBox<String> edugrad_ComboBox;
    private javax.swing.JTextField edugrad_TextField;
    private javax.swing.JComboBox<String> eduhigh_ComboBox;
    private javax.swing.JTextField eduhigh_TextField;
    private javax.swing.JLabel edujLabel;
    private javax.swing.JComboBox<String> eduunder_ComboBox;
    private javax.swing.JTextField eduunder_TextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel emailjLabel;
    private javax.swing.JTextField genderTextField;
    private javax.swing.JLabel genderjLabel;
    private javax.swing.JLabel imgjLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel namejLabel;
    private javax.swing.JTextArea objstateTextArea;
    private javax.swing.JLabel objstatejLabel;
    private javax.swing.JScrollPane objstatejScrollPane;
    private javax.swing.JTextField phoneNumTextField;
    private javax.swing.JLabel phoneNumjLabel;
    private javax.swing.JButton viewBtn;
    private javax.swing.JLabel viewjLabel;
    private javax.swing.JPanel viewjPanel;
    private javax.swing.JScrollPane viewjScrollPane;
    private javax.swing.JScrollPane viewjScrollPane1;
    private javax.swing.JTable viewjTable;
    private javax.swing.JTextArea workhisTextArea;
    private javax.swing.JScrollPane workhisjScrollPane;
    private javax.swing.JLabel workhistoryjLabel;
    // End of variables declaration//GEN-END:variables

   
}
