/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Resume;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author mac
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private Resume info;
    public CreateJPanel(Resume info) {
        initComponents();
        this.info=info;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNamjLabel = new javax.swing.JLabel();
        lastNamjLabel = new javax.swing.JLabel();
        firstnameTextField = new javax.swing.JTextField();
        lastnameTextField = new javax.swing.JTextField();
        addressjLabel = new javax.swing.JLabel();
        addline2TextField = new javax.swing.JTextField();
        addcityTextField = new javax.swing.JTextField();
        addcountryTextField = new javax.swing.JTextField();
        affiliationjLabel = new javax.swing.JLabel();
        objstatejLabel = new javax.swing.JLabel();
        phoneNumjLabel = new javax.swing.JLabel();
        phoneNumTextField = new javax.swing.JTextField();
        workhistoryjLabel = new javax.swing.JLabel();
        abilityjLabel = new javax.swing.JLabel();
        abilityTextField = new javax.swing.JTextField();
        certificatejLabel = new javax.swing.JLabel();
        certificateTextField = new javax.swing.JTextField();
        affiliationTextField = new javax.swing.JTextField();
        genderjLabel = new javax.swing.JLabel();
        imgjLabel = new javax.swing.JLabel();
        imgBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        gender_F_RBtn = new javax.swing.JRadioButton();
        gender_M_RBtn = new javax.swing.JRadioButton();
        eduunder_TextField = new javax.swing.JTextField();
        edugrad_ComboBox = new javax.swing.JComboBox<>();
        edugrad_TextField = new javax.swing.JTextField();
        edujLabel = new javax.swing.JLabel();
        eduhigh_ComboBox = new javax.swing.JComboBox<>();
        eduhigh_TextField = new javax.swing.JTextField();
        eduunder_ComboBox = new javax.swing.JComboBox<>();
        objstateTextField = new javax.swing.JTextField();
        workhisjScrollPane = new javax.swing.JScrollPane();
        workhisTextArea = new javax.swing.JTextArea();
        saveBtn = new javax.swing.JButton();
        addline1TextField = new javax.swing.JTextField();

        firstNamjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        firstNamjLabel.setText("First Name:");

        lastNamjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lastNamjLabel.setText("Last Name:");

        firstnameTextField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        lastnameTextField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        addressjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        addressjLabel.setText("Address:");

        addline2TextField.setForeground(new java.awt.Color(153, 153, 153));
        addline2TextField.setText("Address line2:");
        addline2TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addline2TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addline2TextFieldFocusLost(evt);
            }
        });

        addcityTextField.setForeground(new java.awt.Color(153, 153, 153));
        addcityTextField.setText("City");
        addcityTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addcityTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addcityTextFieldFocusLost(evt);
            }
        });

        addcountryTextField.setForeground(new java.awt.Color(153, 153, 153));
        addcountryTextField.setText("Country");
        addcountryTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addcountryTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addcountryTextFieldFocusLost(evt);
            }
        });

        affiliationjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        affiliationjLabel.setText("Affiliation:");

        objstatejLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        objstatejLabel.setText("Carrer object statement:");

        phoneNumjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        phoneNumjLabel.setText("Phone Number:");

        phoneNumTextField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        phoneNumTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        workhistoryjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        workhistoryjLabel.setText("Work History:");

        abilityjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        abilityjLabel.setText("Ability:");

        certificatejLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        certificatejLabel.setText("Certificate:");

        affiliationTextField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        genderjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        genderjLabel.setText("Gender:");

        imgjLabel.setBackground(new java.awt.Color(255, 255, 255));
        imgjLabel.setForeground(new java.awt.Color(255, 255, 255));
        imgjLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255)));

        imgBtn.setText("choose");
        imgBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgBtnMouseClicked(evt);
            }
        });
        imgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgBtnActionPerformed(evt);
            }
        });

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        gender_F_RBtn.setText("Female");
        gender_F_RBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender_F_RBtnActionPerformed(evt);
            }
        });

        gender_M_RBtn.setText("Male");
        gender_M_RBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender_M_RBtnActionPerformed(evt);
            }
        });

        edugrad_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High school", "Undergraduate", "Graduate" }));
        edugrad_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edugrad_ComboBoxActionPerformed(evt);
            }
        });

        edujLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        edujLabel.setText("Education:");

        eduhigh_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High school", "Undergraduate", "Graduate" }));
        eduhigh_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eduhigh_ComboBoxActionPerformed(evt);
            }
        });

        eduunder_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High school", "Undergraduate", "Graduate" }));
        eduunder_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eduunder_ComboBoxActionPerformed(evt);
            }
        });

        workhisTextArea.setColumns(20);
        workhisTextArea.setRows(5);
        workhisjScrollPane.setViewportView(workhisTextArea);

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        addline1TextField.setForeground(new java.awt.Color(153, 153, 153));
        addline1TextField.setText("Address line1:");
        addline1TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addline1TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addline1TextFieldFocusLost(evt);
            }
        });
        addline1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addline1TextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(workhistoryjLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(workhisjScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(abilityjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(abilityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(objstateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(certificatejLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(certificateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(objstatejLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edujLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edugrad_ComboBox, 0, 1, Short.MAX_VALUE)
                                    .addComponent(eduunder_ComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 1, Short.MAX_VALUE)
                                    .addComponent(eduhigh_ComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eduunder_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eduhigh_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edugrad_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(phoneNumjLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(phoneNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addressjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addline2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addcityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addline1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(firstNamjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lastNamjLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(genderjLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(gender_F_RBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(gender_M_RBtn))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(addcountryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(affiliationjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(affiliationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(110, 110, 110)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(imgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addComponent(imgjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(submitBtn)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(imgjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(addcityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addcountryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(imgBtn)
                                    .addComponent(saveBtn)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(firstNamjLabel)
                                    .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastNamjLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(genderjLabel)
                                    .addComponent(gender_F_RBtn)
                                    .addComponent(gender_M_RBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(phoneNumjLabel)
                                    .addComponent(phoneNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(addressjLabel)
                                    .addComponent(addline1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addline2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(affiliationjLabel)
                        .addComponent(affiliationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edujLabel)
                    .addComponent(eduhigh_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eduhigh_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eduunder_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eduunder_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edugrad_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edugrad_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(workhistoryjLabel)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(workhisjScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abilityjLabel)
                    .addComponent(abilityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(certificatejLabel)
                    .addComponent(certificateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(objstatejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(objstateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitBtn)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        info.setFirstname(firstnameTextField.getText());
        info.setLastname(lastnameTextField.getText());
        info.setPhonenum(phoneNumTextField.getText());
        info.setAddress_1(addline1TextField.getText());
        info.setAddress_2(addline2TextField.getText());
        info.setAddress_city(addcityTextField.getText());
        info.setAddress_country(addcountryTextField.getText());
        
        info.setAffiliation(affiliationTextField.getText());
        info.setEdu_high(eduhigh_TextField.getText());
        info.setEdu_under(eduunder_TextField.getText());
        info.setEdu_graduate(edugrad_TextField.getText());
        
        info.setWorkhistory(workhisTextArea.getText());
        info.setAbility(abilityTextField.getText());
        info.setCertificate(certificateTextField.getText());
        info.setCarreerobjst(objstateTextField.getText());
        
        info.setEdu_highcombox(eduhigh_ComboBox.getSelectedItem().toString());
        info.setEdu_undercombox(eduunder_ComboBox.getSelectedItem().toString());
        info.setEdu_gradcombox(edugrad_ComboBox.getSelectedItem().toString());
        JOptionPane.showMessageDialog(null,"Submit Successfully!");
        
    }//GEN-LAST:event_submitBtnActionPerformed

    public ImageIcon ResizeImage(String ImagePath)
    {
       ImageIcon icon=new ImageIcon(ImagePath);
       Image img=icon.getImage();
       Image newImg=img.getScaledInstance(imgjLabel.getWidth(), imgjLabel.getHeight(), Image.SCALE_SMOOTH);
       ImageIcon imgcon=new ImageIcon(newImg);
       
       return imgcon;
    }
    private void imgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null); 
        File f=chooser.getSelectedFile();
        String filepath=f.getAbsolutePath();
        imgjLabel.setIcon(ResizeImage(filepath));       
    }//GEN-LAST:event_imgBtnActionPerformed

    private void imgBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_imgBtnMouseClicked

    private void gender_F_RBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gender_F_RBtnActionPerformed
        if(gender_F_RBtn.isSelected())
        {
            gender_M_RBtn.setSelected(false);
            info.setGender(gender_F_RBtn.getText());
        }
    }//GEN-LAST:event_gender_F_RBtnActionPerformed

    private void gender_M_RBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gender_M_RBtnActionPerformed
        if(gender_M_RBtn.isSelected())
        {
            gender_F_RBtn.setSelected(false);
            info.setGender(gender_M_RBtn.getText());
        }
    }//GEN-LAST:event_gender_M_RBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        info.setIcon(imgjLabel.getIcon());
        JOptionPane.showMessageDialog(null,"Save the picture");
    }//GEN-LAST:event_saveBtnActionPerformed

    private void eduhigh_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eduhigh_ComboBoxActionPerformed
        info.setEdu_highcombox(eduhigh_ComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_eduhigh_ComboBoxActionPerformed

    private void eduunder_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eduunder_ComboBoxActionPerformed
        info.setEdu_undercombox(eduunder_ComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_eduunder_ComboBoxActionPerformed

    private void edugrad_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edugrad_ComboBoxActionPerformed
        // TODO add your handling code here:
        info.setEdu_gradcombox(edugrad_ComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_edugrad_ComboBoxActionPerformed

    private void addline1TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addline1TextFieldFocusGained
        if(addline1TextField.getText().equals("Address line1:"))
        {   addline1TextField.setText("");
            addline1TextField.setForeground(Color.black);}
    }//GEN-LAST:event_addline1TextFieldFocusGained

    private void addline1TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addline1TextFieldFocusLost
        if(addline1TextField.getText().isEmpty())
        {
            addline1TextField.setForeground(Color.gray);
            addline1TextField.setText("Address line1:");
        }   
    }//GEN-LAST:event_addline1TextFieldFocusLost

    private void addline1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addline1TextFieldActionPerformed
    }//GEN-LAST:event_addline1TextFieldActionPerformed

    private void addline2TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addline2TextFieldFocusGained
        if(addline2TextField.getText().equals("Address line2:"))
        {   addline2TextField.setText("");
            addline2TextField.setForeground(Color.black);}
    }//GEN-LAST:event_addline2TextFieldFocusGained

    private void addline2TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addline2TextFieldFocusLost
        if(addline2TextField.getText().isEmpty())
        {
            addline2TextField.setForeground(Color.gray);
            addline2TextField.setText("Address line2:");
        }   
    }//GEN-LAST:event_addline2TextFieldFocusLost

    private void addcityTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addcityTextFieldFocusGained
        if(addcityTextField.getText().equals("City"))
        {   addcityTextField.setText("");
            addcityTextField.setForeground(Color.black);
        }
    }//GEN-LAST:event_addcityTextFieldFocusGained

    private void addcityTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addcityTextFieldFocusLost
        if(addcityTextField.getText().isEmpty())
        {
            addcityTextField.setForeground(Color.gray);
            addcityTextField.setText("City");
        }
    }//GEN-LAST:event_addcityTextFieldFocusLost

    private void addcountryTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addcountryTextFieldFocusGained
        if(addcountryTextField.getText().equals("Country"))
        {   addcountryTextField.setText("");
            addcountryTextField.setForeground(Color.black);
        }
    }//GEN-LAST:event_addcountryTextFieldFocusGained

    private void addcountryTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addcountryTextFieldFocusLost
        if(addcountryTextField.getText().isEmpty())
        {
            addcountryTextField.setForeground(Color.gray);
            addcountryTextField.setText("Country");
        }
    }//GEN-LAST:event_addcountryTextFieldFocusLost
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField abilityTextField;
    private javax.swing.JLabel abilityjLabel;
    private javax.swing.JTextField addcityTextField;
    private javax.swing.JTextField addcountryTextField;
    private javax.swing.JTextField addline1TextField;
    private javax.swing.JTextField addline2TextField;
    private javax.swing.JLabel addressjLabel;
    private javax.swing.JTextField affiliationTextField;
    private javax.swing.JLabel affiliationjLabel;
    private javax.swing.JTextField certificateTextField;
    private javax.swing.JLabel certificatejLabel;
    private javax.swing.JComboBox<String> edugrad_ComboBox;
    private javax.swing.JTextField edugrad_TextField;
    private javax.swing.JComboBox<String> eduhigh_ComboBox;
    private javax.swing.JTextField eduhigh_TextField;
    private javax.swing.JLabel edujLabel;
    private javax.swing.JComboBox<String> eduunder_ComboBox;
    private javax.swing.JTextField eduunder_TextField;
    private javax.swing.JLabel firstNamjLabel;
    private javax.swing.JTextField firstnameTextField;
    private javax.swing.JRadioButton gender_F_RBtn;
    private javax.swing.JRadioButton gender_M_RBtn;
    private javax.swing.JLabel genderjLabel;
    private javax.swing.JButton imgBtn;
    private javax.swing.JLabel imgjLabel;
    private javax.swing.JLabel lastNamjLabel;
    private javax.swing.JTextField lastnameTextField;
    private javax.swing.JTextField objstateTextField;
    private javax.swing.JLabel objstatejLabel;
    private javax.swing.JTextField phoneNumTextField;
    private javax.swing.JLabel phoneNumjLabel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextArea workhisTextArea;
    private javax.swing.JScrollPane workhisjScrollPane;
    private javax.swing.JLabel workhistoryjLabel;
    // End of variables declaration//GEN-END:variables
}
