/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Resume;
import javax.swing.Icon;

/**
 *
 * @author mac
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    private Resume info;
    public ViewJPanel(Resume info) {
        initComponents();
        displayresume(info);
    }
    
    private void displayresume(Resume info)
    {
        String firstname=info.getFirstname();
        firstnameTextField.setText(firstname);
        String lastname=info.getLastname();
        lastnameTextField.setText(lastname);
        
        String gender=info.getGender();
        genderTextField.setText(gender);
        
        String phoneNum=info.getPhonenum();
        phoneNumTextField.setText(phoneNum);
        
        String addline1=info.getAddress_1();
        addline1TextField.setText(addline1);
        String addline2=info.getAddress_2();
        addline2TextField.setText(addline2);
        String addcity=info.getAddress_city();
        addcityTextField.setText(addcity);
        String addcountry=info.getAddress_country();
        addcountryTextField.setText(addcountry);
        
        
        String affiliation=info.getAffiliation();
        affiliationTextField.setText(affiliation);
        
        String highschool=info.getEdu_high();   
        eduhigh_TextField.setText(highschool);
        String undergraduate=info.getEdu_under();
        eduunder_TextField.setText(undergraduate);
        String graduate=info.getEdu_graduate();
        edugrad_TextField.setText(graduate);
        
        String eduhighCombox=info.getEdu_highcombox();
        eduhigh_ComboBox.setSelectedItem(eduhighCombox);
        String eduunderCombox=info.getEdu_undercombox();
        eduunder_ComboBox.setSelectedItem(eduunderCombox);
        String edugradCombox=info.getEdu_gradcombox();
        edugrad_ComboBox.setSelectedItem(edugradCombox);
        
        String workhistory=info.getWorkhistory();
        workhisTextArea.setText(workhistory);
        String ability=info.getAbility();
        abilityTextField.setText(ability);
        String cert=info.getCertificate();
        certificateTextField.setText(cert);
        String state=info.getCarreerobjst();
        objstateTextField.setText(state);
        
        Icon image=info.getIcon();
        imgjLabel.setIcon(image);
  //      imgjLabel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abilityjLabel = new javax.swing.JLabel();
        certificatejLabel = new javax.swing.JLabel();
        certificateTextField = new javax.swing.JTextField();
        affiliationTextField = new javax.swing.JTextField();
        addcountryTextField = new javax.swing.JTextField();
        affiliationjLabel = new javax.swing.JLabel();
        edujLabel = new javax.swing.JLabel();
        eduhigh_TextField = new javax.swing.JTextField();
        objstatejLabel = new javax.swing.JLabel();
        phoneNumjLabel = new javax.swing.JLabel();
        phoneNumTextField = new javax.swing.JTextField();
        firstNamjLabel = new javax.swing.JLabel();
        lastNamjLabel = new javax.swing.JLabel();
        firstnameTextField = new javax.swing.JTextField();
        lastnameTextField = new javax.swing.JTextField();
        addressjLabel = new javax.swing.JLabel();
        addline1TextField = new javax.swing.JTextField();
        addline2TextField = new javax.swing.JTextField();
        addcityTextField = new javax.swing.JTextField();
        workhistoryjLabel = new javax.swing.JLabel();
        workhisjScrollPane = new javax.swing.JScrollPane();
        workhisTextArea = new javax.swing.JTextArea();
        genderjLabel = new javax.swing.JLabel();
        imgjLabel = new javax.swing.JLabel();
        genderTextField = new javax.swing.JTextField();
        eduunder_TextField = new javax.swing.JTextField();
        edugrad_ComboBox = new javax.swing.JComboBox<>();
        edugrad_TextField = new javax.swing.JTextField();
        objstateTextField = new javax.swing.JTextField();
        eduunder_ComboBox = new javax.swing.JComboBox<>();
        eduhigh_ComboBox = new javax.swing.JComboBox<>();
        abilityTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(240, 243, 243));

        abilityjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        abilityjLabel.setText("Ability:");

        certificatejLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        certificatejLabel.setText("Certificate:");

        certificateTextField.setEditable(false);
        certificateTextField.setBackground(new java.awt.Color(235, 238, 242));

        affiliationTextField.setEditable(false);
        affiliationTextField.setBackground(new java.awt.Color(235, 238, 242));
        affiliationTextField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        addcountryTextField.setEditable(false);
        addcountryTextField.setBackground(new java.awt.Color(235, 238, 242));

        affiliationjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        affiliationjLabel.setText("Affiliation:");

        edujLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        edujLabel.setText("Education:");

        eduhigh_TextField.setEditable(false);
        eduhigh_TextField.setBackground(new java.awt.Color(235, 238, 242));

        objstatejLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        objstatejLabel.setText("Carrer object statement:");

        phoneNumjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        phoneNumjLabel.setText("Phone Number:");

        phoneNumTextField.setEditable(false);
        phoneNumTextField.setBackground(new java.awt.Color(235, 238, 242));
        phoneNumTextField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        firstNamjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        firstNamjLabel.setText("First Name:");

        lastNamjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lastNamjLabel.setText("Last Name:");

        firstnameTextField.setEditable(false);
        firstnameTextField.setBackground(new java.awt.Color(235, 238, 242));
        firstnameTextField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        lastnameTextField.setEditable(false);
        lastnameTextField.setBackground(new java.awt.Color(235, 238, 242));
        lastnameTextField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        addressjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        addressjLabel.setText("Address:");

        addline1TextField.setEditable(false);
        addline1TextField.setBackground(new java.awt.Color(235, 238, 242));
        addline1TextField.setToolTipText("");

        addline2TextField.setEditable(false);
        addline2TextField.setBackground(new java.awt.Color(235, 238, 242));

        addcityTextField.setEditable(false);
        addcityTextField.setBackground(new java.awt.Color(235, 238, 242));

        workhistoryjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        workhistoryjLabel.setText("Work History:");

        workhisTextArea.setEditable(false);
        workhisTextArea.setBackground(new java.awt.Color(235, 238, 242));
        workhisTextArea.setColumns(20);
        workhisTextArea.setRows(5);
        workhisjScrollPane.setViewportView(workhisTextArea);

        genderjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        genderjLabel.setText("Gender:");

        imgjLabel.setBackground(new java.awt.Color(217, 249, 249));
        imgjLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255)));

        genderTextField.setEditable(false);
        genderTextField.setBackground(new java.awt.Color(235, 238, 242));
        genderTextField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        eduunder_TextField.setEditable(false);
        eduunder_TextField.setBackground(new java.awt.Color(235, 238, 242));

        edugrad_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High school", "Undergraduate", "Graduate" }));
        edugrad_ComboBox.setEnabled(false);

        edugrad_TextField.setEditable(false);
        edugrad_TextField.setBackground(new java.awt.Color(235, 238, 242));

        objstateTextField.setEditable(false);
        objstateTextField.setBackground(new java.awt.Color(235, 238, 242));

        eduunder_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High school", "Undergraduate", "Graduate" }));
        eduunder_ComboBox.setEnabled(false);

        eduhigh_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High school", "Undergraduate", "Graduate" }));
        eduhigh_ComboBox.setEnabled(false);

        abilityTextField.setEditable(false);
        abilityTextField.setBackground(new java.awt.Color(235, 238, 242));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(addcityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addcountryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(workhisjScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(certificatejLabel)
                                    .addComponent(abilityjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(certificateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(abilityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(workhistoryjLabel)
                            .addComponent(objstatejLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(objstateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edujLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edugrad_ComboBox, 0, 131, Short.MAX_VALUE)
                                    .addComponent(eduunder_ComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 131, Short.MAX_VALUE)
                                    .addComponent(eduhigh_ComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 131, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eduunder_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eduhigh_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edugrad_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(affiliationjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(affiliationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(110, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addressjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addline2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addline1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(firstNamjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lastNamjLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(genderjLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(phoneNumjLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(phoneNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNamjLabel)
                            .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNamjLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderjLabel)
                            .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneNumjLabel)
                            .addComponent(phoneNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressjLabel)
                            .addComponent(addline1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addline2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imgjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addcityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addcountryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(affiliationjLabel)
                    .addComponent(affiliationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edujLabel)
                    .addComponent(eduhigh_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eduhigh_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eduunder_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eduunder_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edugrad_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edugrad_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workhistoryjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workhisjScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abilityjLabel)
                    .addComponent(abilityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(certificatejLabel)
                    .addComponent(certificateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(objstatejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(objstateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField abilityTextField;
    private javax.swing.JLabel abilityjLabel;
    private javax.swing.JTextField addcityTextField;
    private javax.swing.JTextField addcountryTextField;
    private javax.swing.JTextField addline1TextField;
    private javax.swing.JTextField addline2TextField;
    private javax.swing.JLabel addressjLabel;
    private javax.swing.JTextField affiliationTextField;
    private javax.swing.JLabel affiliationjLabel;
    private javax.swing.JTextField certificateTextField;
    private javax.swing.JLabel certificatejLabel;
    private javax.swing.JComboBox<String> edugrad_ComboBox;
    private javax.swing.JTextField edugrad_TextField;
    private javax.swing.JComboBox<String> eduhigh_ComboBox;
    private javax.swing.JTextField eduhigh_TextField;
    private javax.swing.JLabel edujLabel;
    private javax.swing.JComboBox<String> eduunder_ComboBox;
    private javax.swing.JTextField eduunder_TextField;
    private javax.swing.JLabel firstNamjLabel;
    private javax.swing.JTextField firstnameTextField;
    private javax.swing.JTextField genderTextField;
    private javax.swing.JLabel genderjLabel;
    private javax.swing.JLabel imgjLabel;
    private javax.swing.JLabel lastNamjLabel;
    private javax.swing.JTextField lastnameTextField;
    private javax.swing.JTextField objstateTextField;
    private javax.swing.JLabel objstatejLabel;
    private javax.swing.JTextField phoneNumTextField;
    private javax.swing.JLabel phoneNumjLabel;
    private javax.swing.JTextArea workhisTextArea;
    private javax.swing.JScrollPane workhisjScrollPane;
    private javax.swing.JLabel workhistoryjLabel;
    // End of variables declaration//GEN-END:variables
}
